version: "3.5"
services:
  fucking:
    image: lvinni/russian-warship-go-fuckyourself
    container_name: russian-warship-go-fuckyourself
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
